apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.infraops.michael.io
spec:
  version: v1
  group: infraops.michael.io
  groupPriorityMinimum: 2000
  service:
    name: infraops-service
    namespace: default
  versionPriority: 10
  caBundle: "xxx"


---
apiVersion: v1
kind: Service
metadata:
  name:  infraops-service
  namespace: default
spec:
  type: ExternalName
  externalName: 10.211.55.2
  ports:
    - port: 443
      protocol: TCP