apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cloud-node-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cloud-node-manager
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cloud-node-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cloud-node-manager
subjects:
  - kind: ServiceAccount
    name: k8s-cloud-node-manager
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-cloud-node-manager-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: k8s-cloud-node-manager
type: kubernetes.io/service-account-token

# rbac for myapiserver