apiVersion: v1
kind: ServiceAccount
metadata:
  name: extended-api-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-k8s-extension-api
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extended-api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-k8s-extension-api
subjects:
  - kind: ServiceAccount
    name: extended-api-server
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: extended-api-server-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: extended-api-server
type: kubernetes.io/service-account-token

# rbac for myapiserver